# sink · JDBC MySQL 单表
# curated-section: sink | Jdbc | single
# plugin_input 按上游 plugin_output 改：src / cdc / kafka_src / file_src / fake

Jdbc {
  plugin_input = ["src"]
  url = "jdbc:mysql://127.0.0.1:3306/demo2?serverTimezone=Asia/Shanghai&useSSL=false"
  driver = "com.mysql.cj.jdbc.Driver"
  username = "root"
  password = "{{mysql_password}}"
  # 自动生成 sink sql，insert delete或 upsert,定义了 upsert 后，generate_sink_sql 必须为 true
  generate_sink_sql = true
  # 开启 upsert 模式,开启后自动寻找主键,并使用主键进行 upsert（有则更新，无则插入）
  enable_upsert = false
  # 数据库名称
  database = "demo2"
  # 表名称,如果是 pg oracle 或 sqlserver 需要填写 schema.table
  table = "archive_users"
  # 主键，用于 upsert 模式下，自动寻找主键,也可手动指定
  #primary_keys = ["id"]
  # batch_size 批量插入的条数
  batch_size = 3000
  # 数据保存模式，APPEND_DATA 追加数据，DROP_DATA 删除数据，
  data_save_mode = "APPEND_DATA"
  # 自动建表保存模式，
  # RECREATE_SCHEMA 删表重建
  # CREATE_SCHEMA_WHEN_NOT_EXIST 如果表不存在会自动创建
  # ERROR_WHEN_SCHEMA_NOT_EXIST 如果表不存在会报错
  # IGNORE 如果表不存在会忽略 
  schema_save_mode ="CREATE_SCHEMA_WHEN_NOT_EXIST"
  # 字段大小写，ORIGINAL 不转换，UPPER 大写，LOWER 小写
  field_ide= 'ORIGINAL'
}
