# source · JDBC MySQL 单表
# curated-section: source | Jdbc | single

Jdbc {
  plugin_output = "src"
  url = "jdbc:mysql://127.0.0.1:3306/seatunnel_demo"
  driver = "com.mysql.cj.jdbc.Driver"
  username = "root"
  password = "{{jdbc_password}}"
  table_list = [
    {
      table_path = "seatunnel_demo.users"
    }
  ]
}
