# sink · Kafka canal_json（承接 CDC 多表）
# curated-section: sink | Kafka

Kafka {
  plugin_input = ["cdc_multi"]
  bootstrap.servers = "127.0.0.1:9092"
  topic = "mysql_cdc_canal"
  format = canal_json
}
