# source · FakeSource（冒烟）
# curated-section: source | FakeSource

FakeSource {
  plugin_output = "fake"
  row.num = 16
  schema = {
    fields {
      id = "bigint"
      name = "string"
      score = "int"
    }
  }
}
