# source · MySQL-CDC 多表
# curated-section: source | MySQL-CDC | multi

MySQL-CDC {
  plugin_output = "cdc_multi"
  url = "jdbc:mysql://127.0.0.1:3306/seatunnel_demo"
  username = "cdc_user"
  password = "{{cdc_password}}"
  table-names = [
    "seatunnel_demo.orders"
    "seatunnel_demo.order_items"
    "seatunnel_demo.users"
  ]
  startup.mode = "initial"
}
