# source · HdfsFile JSON
# curated-section: source | HdfsFile

HdfsFile {
  plugin_output = "file_src"
  path = "/apps/hive/demo/student"
  file_format_type = "json"
  fs.defaultFS = "hdfs://namenode001:8020"
  schema = {
    fields {
      name = "string"
      age = "int"
    }
  }
}
