# source · JDBC MySQL 单表
# curated-section: source | Jdbc | single

Jdbc {
  plugin_output = "src"
  url = "jdbc:mysql://127.0.0.1:3306/demo2?serverTimezone=Asia/Shanghai&useSSL=false"
  driver = "com.mysql.cj.jdbc.Driver"
  username = "root"
  password = "{{jdbc_password}}"
  table_list = [
    {
      table_path = "demo2.archive_users"
    }
  ]
  # seatunnel 默认开启动态均衡切分大小（数值类型一般是先预执行查询 min() max(),拿到范围后做切分），
  # 建议全局并行度与切分数量对齐，比如全表100w数据，如果想要 10 个并发，则 split.size = 100000，这样可以避免分片排队现象
  # 如果任务启动长时间没读取数据，那么可能卡在统计信息收集阶段
  split.size = 100000

  # partition_column 是切分列，用于控制分片范围，没写 partition_column 时会自动用主键/唯一索引里第一个可切分列；都不行就单并发
  # partition_column = "id"

  # fetch_size 是 JDBC 查询的 fetch size，用于控制每次查询返回的行数，
  fetch_size = 3000
  
  # 如果想自定义查询语句，可以在这里填写，否则会根据table_path自动生成查询语句
  # 自定语句想要切分，需要手动写 partition_column
  # query = "select * from demo2.archive_users"
  
  # 对于超大数据量表，特别是 oracle,可以开启 skip_analyze 跳过统计信息收集，提高查询性能
  skip_analyze = false
}
